# All values here are for chunk coordinates and distances
spawn-town-chunk-location:
  x: 0
  z: 0
unclaimable-distance: 10
message: "<red>You cannot claim a town this close to spawn"
prevent-block-place: true
prevent-block-break: true
prevent-mob-spawns: true